on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: /home/conan

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu18.04
    env:
      CONAN_HOME: /home/conan/tmp
    steps:

      - name: Check out repository code
        uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan/crawler

      - name: Configure Conan
        run: |
          pip install conan --upgrade
          conan --version
          pip install -r crawler/requirements.txt
          conan profile detect
      - name: Run the script
        run: |
          git clone https://github.com/conan-io/conan-center-index tmp/conan-center-index
          python crawler/crawl.py > crawler/targets-data.json
          rm -rf tmp
          cd crawler
          git remote -v
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add targets-data.json
          git commit -m "update targets-data.json"
          git push origin main
