on: [push, workflow_dispatch]

defaults:
  run:
    working-directory: /home/conan

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu18.04
    env:
      CONAN_HOME: /home/conan/tmp
    steps:

      - name: Check out repository code
        uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan/crawler

      - name: Configure Conan
        run: |
          pip install conan --upgrade
          conan --version
          pip install -r crawler/requirements.txt
          conan profile detect
      - name: Run the script
        run: |
          git clone https://github.com/conan-io/conan-center-index tmp/conan-center-index
          cd crawler
          python crawl.py > targets-data.json
          rm -rf ../tmp
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git fetch origin publish_info
          git checkout publish_info
          git add targets-data.json
          git commit -m "update targets-data.json"
          git push origin publish_info
