on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    working-directory: /home/conan

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu18.04
    env:
      CONAN_HOME: /home/conan/tmp
    steps:

      - name: Check out repository code
        uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan

      - name: Configure Conan
        run: |
          pip install conan --upgrade
          conan --version
          pip install -r requirements.txt
          conan profile detect
      - name: Run the script
        run: |
          git clone https://github.com/conan-io/conan-center-index tmp/conan-center-index
          python crawl.py > targets-data.json
          ls
          rm -rf tmp
          git config --global user.name ${{ secrets.GH_USER }}
          git config --global user.email "${{ secrets.GH_MAIL }}"
          git remote -v
          git add targets-data.json
          git commit -m "update targets-data.json"
          git log
